{
  "gitopsInstance": {
    "schemaVersion": 1,
    "requestScope": "PROJECT",
    "agentScope": "PROJECT",
    "mode": "DEDICATED",
    "orgIdentifier": "data_engineers",
    "projectIdentifier": "data_pipeline_reference",
    "inventoryService": {
      "name": "data_engineers data_pipeline_reference GitOps Instance",
      "identifier": "data_engineers_data_pipeline_reference_gitops_instance",
      "orgIdentifier": "harness_controllers",
      "projectIdentifier": "hub_orchistrator",
      "valuesPath": "hub-clusters/eks-hub/tenants/data-engineers/data-pipeline-reference/values.yaml"
    },
    "agentNamespace": "data-pipeline-reference-argo",
    "agentIdentifier": "data_pipeline_reference_argo_agent"
  },
  "team": "data-pipeline-reference",
  "argocdNamespace": "data-pipeline-reference-argo",
  "workloadNamespaces": [
    "data-pipeline-reference-dev"
  ],
  "projectName": "data-pipeline-reference",
  "sourceRepos": [],
  "harness": {
    "hub": "eks-hub",
    "envRef": "hub",
    "clusterRef": "account.hubcluster",
    "agentRef": "account.hub_account_agent",
    "serviceRef": "data_engineers_data_pipeline_reference_gitops_instance"
  },
  "namespaceLabels": {
    "pod-security.kubernetes.io/enforce": "baseline",
    "pod-security.kubernetes.io/audit": "restricted",
    "pod-security.kubernetes.io/warn": "restricted"
  },
  "deployableKinds": {
    "enabled": false,
    "rules": []
  },
  "rolloutActions": {
    "enabled": false
  },
  "lockDefaultProject": true,
  "harnessAgent": {
    "enabled": true,
    "metadata": {
      "name": "data-pipeline-reference-argo-agent"
    },
    "spec": {
      "name": "data-pipeline-reference-argo-agent",
      "scope": "PROJECT",
      "orgId": "data_engineers",
      "apiKeySecretRef": "harness-api-key-secret",
      "tokenSecretRef": "data-pipeline-reference-argo-agent-token",
      "projectId": "data_pipeline_reference"
    },
    "apiKeySecret": {
      "create": false
    }
  },
  "gitopsAgent": {
    "enabled": true,
    "global": {
      "image": {
        "tag": "v3.3.10"
      }
    },
    "harness": {
      "createClusterRoles": false,
      "gitopsServerHost": "https://app.harness.io/prod1/gitops",
      "identity": {
        "accountIdentifier": "qIYsos1ZQO6fJMG1Ip6KJA",
        "orgIdentifier": "data_engineers",
        "projectIdentifier": "data_pipeline_reference",
        "agentIdentifier": "data_pipeline_reference_argo_agent"
      }
    },
    "agent": {
      "harnessName": "data-pipeline-reference-argo-agent",
      "existingSecrets": {
        "agentToken": "data-pipeline-reference-argo-agent-token"
      }
    },
    "argo-cd": {
      "server": {
        "replicas": 1,
        "serviceAccount": {
          "create": true
        }
      },
      "crds": {
        "install": false,
        "keep": true
      },
      "configs": {
        "params": {
          "server.insecure": "true"
        },
        "rbac": {
          "policy.csv": "g, idp, role:readonly\n"
        },
        "cm": {
          "accounts.idp": "apiKey, login",
          "cluster.inClusterEnabled": "true"
        }
      }
    }
  },
  "projectMappings": [
    {
      "name": "data-pipeline-reference-data-pipeline-reference",
      "appProject": "data-pipeline-reference",
      "orgId": "data_engineers",
      "projectId": "data_pipeline_reference",
      "autoCreateServiceEnv": false
    }
  ],
  "appProject": {
    "enabled": false
  }
}
